# Generated by Django 2.2.3 on 2019-07-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads')),
                ('desc', models.CharField(max_length=10)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ads1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='ads1')),
                ('desc', models.CharField(max_length=10)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ads2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(upload_to='ads2')),
                ('desc', models.CharField(max_length=10)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sp')),
                ('desc', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('uper_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20, null=True)),
                ('create_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('passworld', models.CharField(max_length=20)),
                ('passworld1', models.CharField(max_length=20)),
                ('static', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img0', models.ImageField(null=True, upload_to='detail')),
                ('color', models.CharField(max_length=20, null=True)),
                ('color1', models.CharField(default='红色', max_length=5)),
                ('color2', models.CharField(default='白色', max_length=5)),
                ('color3', models.CharField(default='黑色', max_length=5)),
                ('color4', models.CharField(default='粉色', max_length=5)),
                ('color5', models.CharField(default='灰色', max_length=5)),
                ('size', models.CharField(default='墨绿色', max_length=5)),
                ('num', models.IntegerField()),
                ('vip', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('integral', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True, default='http://baidu.com', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cart')),
            ],
        ),
    ]
