# Generated by Django 2.2.3 on 2019-07-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_title_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='create_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
