# Generated by Django 2.2.3 on 2019-07-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='type',
            field=models.CharField(choices=[('man', '男'), ('women', '女')], default='man', max_length=5),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('women', '女')], max_length=5),
        ),
    ]
